name: 02-Workflow-Events
on: push
jobs:
    echo-hello:
        runs-on: ubuntu-latest
        steps:
            - name: Show the trigger event
              run: echo "I've been triggered by a(n) ${{ github.event_name }} event."
 
    