name: 04-Using-Action

on: push
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
            - name: Serup Node
              uses: actions/setup-node@v3
              with:
                  node-version: 'v25.2.1'
            - name: install dependencies
              run: npm ci
              working-directory: 04-using-actions/reacct-app   



            # - name: Use a third-party action
            #   uses: actions/setup-node@v3
            #   with:
            #       node-version: '14'

            # - name: Verify Node.js installation
            #   run: |
            #       node -v
            #       npm -v